// One-shot: read Finance-Bill-2026.pdf → write lib/billContext.ts
// Run: node scripts/extract-bill.mjs
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const pdfParse = require("pdf-parse");

const __dirname = dirname(fileURLToPath(import.meta.url));
const PDF_PATH = resolve(__dirname, "../../Finance-Bill-2026.pdf");
const OUT_PATH = resolve(__dirname, "../lib/billContext.ts");

const buf = await readFile(PDF_PATH);
const { text } = await pdfParse(buf);

const escaped = text
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const out = `// Generated by scripts/extract-bill.mjs — do not edit by hand.
// Source: Finance-Bill-2026.pdf (gazetted 30 April 2026).

export const BILL_GAZETTE_DATE = "30 April 2026";

export const BILL_CONTEXT = \`${escaped}\`;
`;

await writeFile(OUT_PATH, out, "utf8");
console.log(`Wrote ${OUT_PATH} (${text.length} chars).`);
